name: 'Hola Mundo'
description: 'Saludar a alguien'

inputs: 
  who-to-greet: # id of input
   description: 'A quien saludar'
   required: true
   default: 'Mundo'

outputs:
  time: # id of input
    description: 'La fecha en la que nos conocimos'

runs:
  using: 'docker'
  image: 'Dockerfile'
  with:
    entrypoint: /entrypoint.sh
  args:
    - ${{ inputs.who-to-greet }}

    
